"""Paper-only trading domain contracts."""

from app.paper_trading.contracts import (
    AssetClass,
    AuditOutcome,
    AuditResourceType,
    OrderIntentStatus,
    OrderSide,
    OrderSource,
    OrderType,
    OptionIntentMetadata,
    PaperAccount,
    PaperAccountStatus,
    PaperAuditEvent,
    PaperFill,
    PaperOrderIntent,
    PaperPosition,
    RiskDecision,
    RiskDecisionResult,
    RiskGuardInput,
    RiskGuardLimits,
    TimeInForce,
)
from app.paper_trading.risk_guard import evaluate_order_intent

__all__ = [
    "AssetClass",
    "AuditOutcome",
    "AuditResourceType",
    "OrderIntentStatus",
    "OrderSide",
    "OrderSource",
    "OrderType",
    "OptionIntentMetadata",
    "PaperAccount",
    "PaperAccountStatus",
    "PaperAuditEvent",
    "PaperFill",
    "PaperOrderIntent",
    "PaperPosition",
    "RiskDecision",
    "RiskDecisionResult",
    "RiskGuardInput",
    "RiskGuardLimits",
    "TimeInForce",
    "evaluate_order_intent",
]
